<?php
/*
* This file is part of the OrbitaleImageMagickPHP package.
*
* (c) Alexandre Rock Ancelet <alex@orbitale.io>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace Orbitale\Component\ImageMagick\Tests;

use Orbitale\Component\ImageMagick\Command;
use Orbitale\Component\ImageMagick\ReferenceClasses\Geometry;

class GeometryTest extends AbstractTestCase
{

    /**
     * @dataProvider provideStaticCreations
     */
    public function testStaticCreation($expect, $width, $height, $x, $y, $aspectRatio)
    {
        $this->markTestIncomplete('TODO'); // TODO
    }

    public function provideStaticCreations()
    {
        return array(
            array('100x100^+0+0', 100, 100, 0, 0, Geometry::RATIO_MIN),
            array('x100^+0+0', null, 100, 0, 0, Geometry::RATIO_MIN),
        );
    }

    /**
     * @dataProvider provideRightGeometries
     */
    public function testGeometry($width, $height, $x, $y, $aspectRatio)
    {
        $geometry = new Geometry($width, $height, $x, $y, $aspectRatio);

        try {
            $validatedGeometry = $geometry->validate();
        } catch (\Exception $e) {
            $this->fail($e->getMessage());
            return;
        }

        $this->assertInternalType('string', $validatedGeometry);
        $this->assertNotEmpty($validatedGeometry);

        if (0 === strlen($validatedGeometry)) {
            $this->markTestSkipped('No geometry to check. ['.$validatedGeometry.'] ['.implode(',', func_get_args()).']');
        }

        $command = new Command(IMAGEMAGICK_DIR);

        $command
            ->convert($this->resourcesDir.'/moon_180.jpg')
            ->resize($geometry)
            ->file($this->resourcesDir.'/outputs/moon_180_test_geometry_'.uniqid($width.$height.$x.$y.$aspectRatio.'test_geo', true).'.jpg', false)
        ;

        $response = $command->run(Command::RUN_DEBUG);

        $this->assertFalse($response->hasFailed(), "For geometry ".$geometry->validate().", ImageMagick error:\n".$response->getContent(true));
    }

    public function provideRightGeometries()
    {
        // width, height, x, y, aspectRatio
        return array(
            array(null, null, null, 0, null),
            array(null, null, null, -1, null),
            array(null, null, null, 1, null),
            array(null, null, 0, null, null),
            array(null, null, 0, 0, null),
            array(null, null, 0, -1, null),
            array(null, null, 0, 1, null),
            array(null, null, -1, null, null),
            array(null, null, -1, 0, null),
            array(null, null, -1, -1, null),
            array(null, null, -1, 1, null),
            array(null, null, 1, null, null),
            array(null, null, 1, 0, null),
            array(null, null, 1, -1, null),
            array(null, null, 1, 1, null),
            array(null, 100, null, null, null),
            array(null, 100, null, null, '<'),
            array(null, 100, null, null, '!'),
            array(null, 100, null, null, '^'),
            array(null, 100, null, null, '>'),
            array(null, 100, null, 0, null),
            array(null, 100, null, 0, '<'),
            array(null, 100, null, 0, '!'),
            array(null, 100, null, 0, '^'),
            array(null, 100, null, 0, '>'),
            array(null, 100, null, -1, null),
            array(null, 100, null, -1, '<'),
            array(null, 100, null, -1, '!'),
            array(null, 100, null, -1, '^'),
            array(null, 100, null, -1, '>'),
            array(null, 100, null, 1, null),
            array(null, 100, null, 1, '<'),
            array(null, 100, null, 1, '!'),
            array(null, 100, null, 1, '^'),
            array(null, 100, null, 1, '>'),
            array(null, 100, 0, null, null),
            array(null, 100, 0, null, '<'),
            array(null, 100, 0, null, '!'),
            array(null, 100, 0, null, '^'),
            array(null, 100, 0, null, '>'),
            array(null, 100, 0, 0, null),
            array(null, 100, 0, 0, '<'),
            array(null, 100, 0, 0, '!'),
            array(null, 100, 0, 0, '^'),
            array(null, 100, 0, 0, '>'),
            array(null, 100, 0, -1, null),
            array(null, 100, 0, -1, '<'),
            array(null, 100, 0, -1, '!'),
            array(null, 100, 0, -1, '^'),
            array(null, 100, 0, -1, '>'),
            array(null, 100, 0, 1, null),
            array(null, 100, 0, 1, '<'),
            array(null, 100, 0, 1, '!'),
            array(null, 100, 0, 1, '^'),
            array(null, 100, 0, 1, '>'),
            array(null, 100, -1, null, null),
            array(null, 100, -1, null, '<'),
            array(null, 100, -1, null, '!'),
            array(null, 100, -1, null, '^'),
            array(null, 100, -1, null, '>'),
            array(null, 100, -1, 0, null),
            array(null, 100, -1, 0, '<'),
            array(null, 100, -1, 0, '!'),
            array(null, 100, -1, 0, '^'),
            array(null, 100, -1, 0, '>'),
            array(null, 100, -1, -1, null),
            array(null, 100, -1, -1, '<'),
            array(null, 100, -1, -1, '!'),
            array(null, 100, -1, -1, '^'),
            array(null, 100, -1, -1, '>'),
            array(null, 100, -1, 1, null),
            array(null, 100, -1, 1, '<'),
            array(null, 100, -1, 1, '!'),
            array(null, 100, -1, 1, '^'),
            array(null, 100, -1, 1, '>'),
            array(null, 100, 1, null, null),
            array(null, 100, 1, null, '<'),
            array(null, 100, 1, null, '!'),
            array(null, 100, 1, null, '^'),
            array(null, 100, 1, null, '>'),
            array(null, 100, 1, 0, null),
            array(null, 100, 1, 0, '<'),
            array(null, 100, 1, 0, '!'),
            array(null, 100, 1, 0, '^'),
            array(null, 100, 1, 0, '>'),
            array(null, 100, 1, -1, null),
            array(null, 100, 1, -1, '<'),
            array(null, 100, 1, -1, '!'),
            array(null, 100, 1, -1, '^'),
            array(null, 100, 1, -1, '>'),
            array(null, 100, 1, 1, null),
            array(null, 100, 1, 1, '<'),
            array(null, 100, 1, 1, '!'),
            array(null, 100, 1, 1, '^'),
            array(null, 100, 1, 1, '>'),
            array(100, null, null, null, null),
            array(100, null, null, null, '<'),
            array(100, null, null, null, '!'),
            array(100, null, null, null, '^'),
            array(100, null, null, null, '>'),
            array(100, null, null, 0, null),
            array(100, null, null, 0, '<'),
            array(100, null, null, 0, '!'),
            array(100, null, null, 0, '^'),
            array(100, null, null, 0, '>'),
            array(100, null, null, -1, null),
            array(100, null, null, -1, '<'),
            array(100, null, null, -1, '!'),
            array(100, null, null, -1, '^'),
            array(100, null, null, -1, '>'),
            array(100, null, null, 1, null),
            array(100, null, null, 1, '<'),
            array(100, null, null, 1, '!'),
            array(100, null, null, 1, '^'),
            array(100, null, null, 1, '>'),
            array(100, null, 0, null, null),
            array(100, null, 0, null, '<'),
            array(100, null, 0, null, '!'),
            array(100, null, 0, null, '^'),
            array(100, null, 0, null, '>'),
            array(100, null, 0, 0, null),
            array(100, null, 0, 0, '<'),
            array(100, null, 0, 0, '!'),
            array(100, null, 0, 0, '^'),
            array(100, null, 0, 0, '>'),
            array(100, null, 0, -1, null),
            array(100, null, 0, -1, '<'),
            array(100, null, 0, -1, '!'),
            array(100, null, 0, -1, '^'),
            array(100, null, 0, -1, '>'),
            array(100, null, 0, 1, null),
            array(100, null, 0, 1, '<'),
            array(100, null, 0, 1, '!'),
            array(100, null, 0, 1, '^'),
            array(100, null, 0, 1, '>'),
            array(100, null, -1, null, null),
            array(100, null, -1, null, '<'),
            array(100, null, -1, null, '!'),
            array(100, null, -1, null, '^'),
            array(100, null, -1, null, '>'),
            array(100, null, -1, 0, null),
            array(100, null, -1, 0, '<'),
            array(100, null, -1, 0, '!'),
            array(100, null, -1, 0, '^'),
            array(100, null, -1, 0, '>'),
            array(100, null, -1, -1, null),
            array(100, null, -1, -1, '<'),
            array(100, null, -1, -1, '!'),
            array(100, null, -1, -1, '^'),
            array(100, null, -1, -1, '>'),
            array(100, null, -1, 1, null),
            array(100, null, -1, 1, '<'),
            array(100, null, -1, 1, '!'),
            array(100, null, -1, 1, '^'),
            array(100, null, -1, 1, '>'),
            array(100, null, 1, null, null),
            array(100, null, 1, null, '<'),
            array(100, null, 1, null, '!'),
            array(100, null, 1, null, '^'),
            array(100, null, 1, null, '>'),
            array(100, null, 1, 0, null),
            array(100, null, 1, 0, '<'),
            array(100, null, 1, 0, '!'),
            array(100, null, 1, 0, '^'),
            array(100, null, 1, 0, '>'),
            array(100, null, 1, -1, null),
            array(100, null, 1, -1, '<'),
            array(100, null, 1, -1, '!'),
            array(100, null, 1, -1, '^'),
            array(100, null, 1, -1, '>'),
            array(100, null, 1, 1, null),
            array(100, null, 1, 1, '<'),
            array(100, null, 1, 1, '!'),
            array(100, null, 1, 1, '^'),
            array(100, null, 1, 1, '>'),
            array(100, 100, null, null, null),
            array(100, 100, null, null, '<'),
            array(100, 100, null, null, '!'),
            array(100, 100, null, null, '^'),
            array(100, 100, null, null, '>'),
            array(100, 100, null, 0, null),
            array(100, 100, null, 0, '<'),
            array(100, 100, null, 0, '!'),
            array(100, 100, null, 0, '^'),
            array(100, 100, null, 0, '>'),
            array(100, 100, null, -1, null),
            array(100, 100, null, -1, '<'),
            array(100, 100, null, -1, '!'),
            array(100, 100, null, -1, '^'),
            array(100, 100, null, -1, '>'),
            array(100, 100, null, 1, null),
            array(100, 100, null, 1, '<'),
            array(100, 100, null, 1, '!'),
            array(100, 100, null, 1, '^'),
            array(100, 100, null, 1, '>'),
            array(100, 100, 0, null, null),
            array(100, 100, 0, null, '<'),
            array(100, 100, 0, null, '!'),
            array(100, 100, 0, null, '^'),
            array(100, 100, 0, null, '>'),
            array(100, 100, 0, 0, null),
            array(100, 100, 0, 0, '<'),
            array(100, 100, 0, 0, '!'),
            array(100, 100, 0, 0, '^'),
            array(100, 100, 0, 0, '>'),
            array(100, 100, 0, -1, null),
            array(100, 100, 0, -1, '<'),
            array(100, 100, 0, -1, '!'),
            array(100, 100, 0, -1, '^'),
            array(100, 100, 0, -1, '>'),
            array(100, 100, 0, 1, null),
            array(100, 100, 0, 1, '<'),
            array(100, 100, 0, 1, '!'),
            array(100, 100, 0, 1, '^'),
            array(100, 100, 0, 1, '>'),
            array(100, 100, -1, null, null),
            array(100, 100, -1, null, '<'),
            array(100, 100, -1, null, '!'),
            array(100, 100, -1, null, '^'),
            array(100, 100, -1, null, '>'),
            array(100, 100, -1, 0, null),
            array(100, 100, -1, 0, '<'),
            array(100, 100, -1, 0, '!'),
            array(100, 100, -1, 0, '^'),
            array(100, 100, -1, 0, '>'),
            array(100, 100, -1, -1, null),
            array(100, 100, -1, -1, '<'),
            array(100, 100, -1, -1, '!'),
            array(100, 100, -1, -1, '^'),
            array(100, 100, -1, -1, '>'),
            array(100, 100, -1, 1, null),
            array(100, 100, -1, 1, '<'),
            array(100, 100, -1, 1, '!'),
            array(100, 100, -1, 1, '^'),
            array(100, 100, -1, 1, '>'),
            array(100, 100, 1, null, null),
            array(100, 100, 1, null, '<'),
            array(100, 100, 1, null, '!'),
            array(100, 100, 1, null, '^'),
            array(100, 100, 1, null, '>'),
            array(100, 100, 1, 0, null),
            array(100, 100, 1, 0, '<'),
            array(100, 100, 1, 0, '!'),
            array(100, 100, 1, 0, '^'),
            array(100, 100, 1, 0, '>'),
            array(100, 100, 1, -1, null),
            array(100, 100, 1, -1, '<'),
            array(100, 100, 1, -1, '!'),
            array(100, 100, 1, -1, '^'),
            array(100, 100, 1, -1, '>'),
            array(100, 100, 1, 1, null),
            array(100, 100, 1, 1, '<'),
            array(100, 100, 1, 1, '!'),
            array(100, 100, 1, 1, '^'),
            array(100, 100, 1, 1, '>'))
            ;
    }

    /**
     * @dataProvider provideWrongGeometries
     */
    public function testWrongGeometry($width, $height, $x, $y, $aspectRatio)
    {
        $geometry = new Geometry($width, $height, $x, $y, $aspectRatio);

        $expectedGeometry = Geometry::createFromParameters($width, $height, $x, $y, $aspectRatio);

        $message = $validatedGeometry = null;

        try {
            $validatedGeometry = $geometry->validate();
        } catch (\InvalidArgumentException $e) {
            $message = $e->getMessage();
        }

        $this->assertNotNull($message, 'No exception for geometry "'.$expectedGeometry.'"');
        $this->assertStringStartsWith('The specified geometry ('.$expectedGeometry.') is invalid.', $message, "Wrong exception message:\n$message");
    }

    public function provideWrongGeometries()
    {
        return array(
            array(null, null, null, null, '<'),
            array(null, null, null, null, '!'),
            array(null, null, null, null, '^'),
            array(null, null, null, null, '>'),
            array(null, null, null, 0, '<'),
            array(null, null, null, 0, '!'),
            array(null, null, null, 0, '^'),
            array(null, null, null, 0, '>'),
            array(null, null, null, -1, '<'),
            array(null, null, null, -1, '!'),
            array(null, null, null, -1, '^'),
            array(null, null, null, -1, '>'),
            array(null, null, null, 1, '<'),
            array(null, null, null, 1, '!'),
            array(null, null, null, 1, '^'),
            array(null, null, null, 1, '>'),
            array(null, null, 0, null, '<'),
            array(null, null, 0, null, '!'),
            array(null, null, 0, null, '^'),
            array(null, null, 0, null, '>'),
            array(null, null, 0, 0, '<'),
            array(null, null, 0, 0, '!'),
            array(null, null, 0, 0, '^'),
            array(null, null, 0, 0, '>'),
            array(null, null, 0, -1, '<'),
            array(null, null, 0, -1, '!'),
            array(null, null, 0, -1, '^'),
            array(null, null, 0, -1, '>'),
            array(null, null, 0, 1, '<'),
            array(null, null, 0, 1, '!'),
            array(null, null, 0, 1, '^'),
            array(null, null, 0, 1, '>'),
            array(null, null, -1, null, '<'),
            array(null, null, -1, null, '!'),
            array(null, null, -1, null, '^'),
            array(null, null, -1, null, '>'),
            array(null, null, -1, 0, '<'),
            array(null, null, -1, 0, '!'),
            array(null, null, -1, 0, '^'),
            array(null, null, -1, 0, '>'),
            array(null, null, -1, -1, '<'),
            array(null, null, -1, -1, '!'),
            array(null, null, -1, -1, '^'),
            array(null, null, -1, -1, '>'),
            array(null, null, -1, 1, '<'),
            array(null, null, -1, 1, '!'),
            array(null, null, -1, 1, '^'),
            array(null, null, -1, 1, '>'),
            array(null, null, 1, null, '<'),
            array(null, null, 1, null, '!'),
            array(null, null, 1, null, '^'),
            array(null, null, 1, null, '>'),
            array(null, null, 1, 0, '<'),
            array(null, null, 1, 0, '!'),
            array(null, null, 1, 0, '^'),
            array(null, null, 1, 0, '>'),
            array(null, null, 1, -1, '<'),
            array(null, null, 1, -1, '!'),
            array(null, null, 1, -1, '^'),
            array(null, null, 1, -1, '>'),
            array(null, null, 1, 1, '<'),
            array(null, null, 1, 1, '!'),
            array(null, null, 1, 1, '^'),
            array(null, null, 1, 1, '>'),
            array(null, 0, null, null, null),
            array(null, 0, null, null, '<'),
            array(null, 0, null, null, '!'),
            array(null, 0, null, null, '^'),
            array(null, 0, null, null, '>'),
            array(null, 0, null, 0, null),
            array(null, 0, null, 0, '<'),
            array(null, 0, null, 0, '!'),
            array(null, 0, null, 0, '^'),
            array(null, 0, null, 0, '>'),
            array(null, 0, null, -1, null),
            array(null, 0, null, -1, '<'),
            array(null, 0, null, -1, '!'),
            array(null, 0, null, -1, '^'),
            array(null, 0, null, -1, '>'),
            array(null, 0, null, 1, null),
            array(null, 0, null, 1, '<'),
            array(null, 0, null, 1, '!'),
            array(null, 0, null, 1, '^'),
            array(null, 0, null, 1, '>'),
            array(null, 0, 0, null, null),
            array(null, 0, 0, null, '<'),
            array(null, 0, 0, null, '!'),
            array(null, 0, 0, null, '^'),
            array(null, 0, 0, null, '>'),
            array(null, 0, 0, 0, null),
            array(null, 0, 0, 0, '<'),
            array(null, 0, 0, 0, '!'),
            array(null, 0, 0, 0, '^'),
            array(null, 0, 0, 0, '>'),
            array(null, 0, 0, -1, null),
            array(null, 0, 0, -1, '<'),
            array(null, 0, 0, -1, '!'),
            array(null, 0, 0, -1, '^'),
            array(null, 0, 0, -1, '>'),
            array(null, 0, 0, 1, null),
            array(null, 0, 0, 1, '<'),
            array(null, 0, 0, 1, '!'),
            array(null, 0, 0, 1, '^'),
            array(null, 0, 0, 1, '>'),
            array(null, 0, -1, null, null),
            array(null, 0, -1, null, '<'),
            array(null, 0, -1, null, '!'),
            array(null, 0, -1, null, '^'),
            array(null, 0, -1, null, '>'),
            array(null, 0, -1, 0, null),
            array(null, 0, -1, 0, '<'),
            array(null, 0, -1, 0, '!'),
            array(null, 0, -1, 0, '^'),
            array(null, 0, -1, 0, '>'),
            array(null, 0, -1, -1, null),
            array(null, 0, -1, -1, '<'),
            array(null, 0, -1, -1, '!'),
            array(null, 0, -1, -1, '^'),
            array(null, 0, -1, -1, '>'),
            array(null, 0, -1, 1, null),
            array(null, 0, -1, 1, '<'),
            array(null, 0, -1, 1, '!'),
            array(null, 0, -1, 1, '^'),
            array(null, 0, -1, 1, '>'),
            array(null, 0, 1, null, null),
            array(null, 0, 1, null, '<'),
            array(null, 0, 1, null, '!'),
            array(null, 0, 1, null, '^'),
            array(null, 0, 1, null, '>'),
            array(null, 0, 1, 0, null),
            array(null, 0, 1, 0, '<'),
            array(null, 0, 1, 0, '!'),
            array(null, 0, 1, 0, '^'),
            array(null, 0, 1, 0, '>'),
            array(null, 0, 1, -1, null),
            array(null, 0, 1, -1, '<'),
            array(null, 0, 1, -1, '!'),
            array(null, 0, 1, -1, '^'),
            array(null, 0, 1, -1, '>'),
            array(null, 0, 1, 1, null),
            array(null, 0, 1, 1, '<'),
            array(null, 0, 1, 1, '!'),
            array(null, 0, 1, 1, '^'),
            array(null, 0, 1, 1, '>'),
            array(0, null, null, null, null),
            array(0, null, null, null, '<'),
            array(0, null, null, null, '!'),
            array(0, null, null, null, '^'),
            array(0, null, null, null, '>'),
            array(0, null, null, 0, null),
            array(0, null, null, 0, '<'),
            array(0, null, null, 0, '!'),
            array(0, null, null, 0, '^'),
            array(0, null, null, 0, '>'),
            array(0, null, null, -1, null),
            array(0, null, null, -1, '<'),
            array(0, null, null, -1, '!'),
            array(0, null, null, -1, '^'),
            array(0, null, null, -1, '>'),
            array(0, null, null, 1, null),
            array(0, null, null, 1, '<'),
            array(0, null, null, 1, '!'),
            array(0, null, null, 1, '^'),
            array(0, null, null, 1, '>'),
            array(0, null, 0, null, null),
            array(0, null, 0, null, '<'),
            array(0, null, 0, null, '!'),
            array(0, null, 0, null, '^'),
            array(0, null, 0, null, '>'),
            array(0, null, 0, 0, null),
            array(0, null, 0, 0, '<'),
            array(0, null, 0, 0, '!'),
            array(0, null, 0, 0, '^'),
            array(0, null, 0, 0, '>'),
            array(0, null, 0, -1, null),
            array(0, null, 0, -1, '<'),
            array(0, null, 0, -1, '!'),
            array(0, null, 0, -1, '^'),
            array(0, null, 0, -1, '>'),
            array(0, null, 0, 1, null),
            array(0, null, 0, 1, '<'),
            array(0, null, 0, 1, '!'),
            array(0, null, 0, 1, '^'),
            array(0, null, 0, 1, '>'),
            array(0, null, -1, null, null),
            array(0, null, -1, null, '<'),
            array(0, null, -1, null, '!'),
            array(0, null, -1, null, '^'),
            array(0, null, -1, null, '>'),
            array(0, null, -1, 0, null),
            array(0, null, -1, 0, '<'),
            array(0, null, -1, 0, '!'),
            array(0, null, -1, 0, '^'),
            array(0, null, -1, 0, '>'),
            array(0, null, -1, -1, null),
            array(0, null, -1, -1, '<'),
            array(0, null, -1, -1, '!'),
            array(0, null, -1, -1, '^'),
            array(0, null, -1, -1, '>'),
            array(0, null, -1, 1, null),
            array(0, null, -1, 1, '<'),
            array(0, null, -1, 1, '!'),
            array(0, null, -1, 1, '^'),
            array(0, null, -1, 1, '>'),
            array(0, null, 1, null, null),
            array(0, null, 1, null, '<'),
            array(0, null, 1, null, '!'),
            array(0, null, 1, null, '^'),
            array(0, null, 1, null, '>'),
            array(0, null, 1, 0, null),
            array(0, null, 1, 0, '<'),
            array(0, null, 1, 0, '!'),
            array(0, null, 1, 0, '^'),
            array(0, null, 1, 0, '>'),
            array(0, null, 1, -1, null),
            array(0, null, 1, -1, '<'),
            array(0, null, 1, -1, '!'),
            array(0, null, 1, -1, '^'),
            array(0, null, 1, -1, '>'),
            array(0, null, 1, 1, null),
            array(0, null, 1, 1, '<'),
            array(0, null, 1, 1, '!'),
            array(0, null, 1, 1, '^'),
            array(0, null, 1, 1, '>'),
            array(0, 0, null, null, null),
            array(0, 0, null, null, '<'),
            array(0, 0, null, null, '!'),
            array(0, 0, null, null, '^'),
            array(0, 0, null, null, '>'),
            array(0, 0, null, 0, null),
            array(0, 0, null, 0, '<'),
            array(0, 0, null, 0, '!'),
            array(0, 0, null, 0, '^'),
            array(0, 0, null, 0, '>'),
            array(0, 0, null, -1, null),
            array(0, 0, null, -1, '<'),
            array(0, 0, null, -1, '!'),
            array(0, 0, null, -1, '^'),
            array(0, 0, null, -1, '>'),
            array(0, 0, null, 1, null),
            array(0, 0, null, 1, '<'),
            array(0, 0, null, 1, '!'),
            array(0, 0, null, 1, '^'),
            array(0, 0, null, 1, '>'),
            array(0, 0, 0, null, null),
            array(0, 0, 0, null, '<'),
            array(0, 0, 0, null, '!'),
            array(0, 0, 0, null, '^'),
            array(0, 0, 0, null, '>'),
            array(0, 0, 0, 0, null),
            array(0, 0, 0, 0, '<'),
            array(0, 0, 0, 0, '!'),
            array(0, 0, 0, 0, '^'),
            array(0, 0, 0, 0, '>'),
            array(0, 0, 0, -1, null),
            array(0, 0, 0, -1, '<'),
            array(0, 0, 0, -1, '!'),
            array(0, 0, 0, -1, '^'),
            array(0, 0, 0, -1, '>'),
            array(0, 0, 0, 1, null),
            array(0, 0, 0, 1, '<'),
            array(0, 0, 0, 1, '!'),
            array(0, 0, 0, 1, '^'),
            array(0, 0, 0, 1, '>'),
            array(0, 0, -1, null, null),
            array(0, 0, -1, null, '<'),
            array(0, 0, -1, null, '!'),
            array(0, 0, -1, null, '^'),
            array(0, 0, -1, null, '>'),
            array(0, 0, -1, 0, null),
            array(0, 0, -1, 0, '<'),
            array(0, 0, -1, 0, '!'),
            array(0, 0, -1, 0, '^'),
            array(0, 0, -1, 0, '>'),
            array(0, 0, -1, -1, null),
            array(0, 0, -1, -1, '<'),
            array(0, 0, -1, -1, '!'),
            array(0, 0, -1, -1, '^'),
            array(0, 0, -1, -1, '>'),
            array(0, 0, -1, 1, null),
            array(0, 0, -1, 1, '<'),
            array(0, 0, -1, 1, '!'),
            array(0, 0, -1, 1, '^'),
            array(0, 0, -1, 1, '>'),
            array(0, 0, 1, null, null),
            array(0, 0, 1, null, '<'),
            array(0, 0, 1, null, '!'),
            array(0, 0, 1, null, '^'),
            array(0, 0, 1, null, '>'),
            array(0, 0, 1, 0, null),
            array(0, 0, 1, 0, '<'),
            array(0, 0, 1, 0, '!'),
            array(0, 0, 1, 0, '^'),
            array(0, 0, 1, 0, '>'),
            array(0, 0, 1, -1, null),
            array(0, 0, 1, -1, '<'),
            array(0, 0, 1, -1, '!'),
            array(0, 0, 1, -1, '^'),
            array(0, 0, 1, -1, '>'),
            array(0, 0, 1, 1, null),
            array(0, 0, 1, 1, '<'),
            array(0, 0, 1, 1, '!'),
            array(0, 0, 1, 1, '^'),
            array(0, 0, 1, 1, '>'),
            array(0, 100, null, null, null),
            array(0, 100, null, null, '<'),
            array(0, 100, null, null, '!'),
            array(0, 100, null, null, '^'),
            array(0, 100, null, null, '>'),
            array(0, 100, null, 0, null),
            array(0, 100, null, 0, '<'),
            array(0, 100, null, 0, '!'),
            array(0, 100, null, 0, '^'),
            array(0, 100, null, 0, '>'),
            array(0, 100, null, -1, null),
            array(0, 100, null, -1, '<'),
            array(0, 100, null, -1, '!'),
            array(0, 100, null, -1, '^'),
            array(0, 100, null, -1, '>'),
            array(0, 100, null, 1, null),
            array(0, 100, null, 1, '<'),
            array(0, 100, null, 1, '!'),
            array(0, 100, null, 1, '^'),
            array(0, 100, null, 1, '>'),
            array(0, 100, 0, null, null),
            array(0, 100, 0, null, '<'),
            array(0, 100, 0, null, '!'),
            array(0, 100, 0, null, '^'),
            array(0, 100, 0, null, '>'),
            array(0, 100, 0, 0, null),
            array(0, 100, 0, 0, '<'),
            array(0, 100, 0, 0, '!'),
            array(0, 100, 0, 0, '^'),
            array(0, 100, 0, 0, '>'),
            array(0, 100, 0, -1, null),
            array(0, 100, 0, -1, '<'),
            array(0, 100, 0, -1, '!'),
            array(0, 100, 0, -1, '^'),
            array(0, 100, 0, -1, '>'),
            array(0, 100, 0, 1, null),
            array(0, 100, 0, 1, '<'),
            array(0, 100, 0, 1, '!'),
            array(0, 100, 0, 1, '^'),
            array(0, 100, 0, 1, '>'),
            array(0, 100, -1, null, null),
            array(0, 100, -1, null, '<'),
            array(0, 100, -1, null, '!'),
            array(0, 100, -1, null, '^'),
            array(0, 100, -1, null, '>'),
            array(0, 100, -1, 0, null),
            array(0, 100, -1, 0, '<'),
            array(0, 100, -1, 0, '!'),
            array(0, 100, -1, 0, '^'),
            array(0, 100, -1, 0, '>'),
            array(0, 100, -1, -1, null),
            array(0, 100, -1, -1, '<'),
            array(0, 100, -1, -1, '!'),
            array(0, 100, -1, -1, '^'),
            array(0, 100, -1, -1, '>'),
            array(0, 100, -1, 1, null),
            array(0, 100, -1, 1, '<'),
            array(0, 100, -1, 1, '!'),
            array(0, 100, -1, 1, '^'),
            array(0, 100, -1, 1, '>'),
            array(0, 100, 1, null, null),
            array(0, 100, 1, null, '<'),
            array(0, 100, 1, null, '!'),
            array(0, 100, 1, null, '^'),
            array(0, 100, 1, null, '>'),
            array(0, 100, 1, 0, null),
            array(0, 100, 1, 0, '<'),
            array(0, 100, 1, 0, '!'),
            array(0, 100, 1, 0, '^'),
            array(0, 100, 1, 0, '>'),
            array(0, 100, 1, -1, null),
            array(0, 100, 1, -1, '<'),
            array(0, 100, 1, -1, '!'),
            array(0, 100, 1, -1, '^'),
            array(0, 100, 1, -1, '>'),
            array(0, 100, 1, 1, null),
            array(0, 100, 1, 1, '<'),
            array(0, 100, 1, 1, '!'),
            array(0, 100, 1, 1, '^'),
            array(0, 100, 1, 1, '>'),
            array(100, 0, null, null, null),
            array(100, 0, null, null, '<'),
            array(100, 0, null, null, '!'),
            array(100, 0, null, null, '^'),
            array(100, 0, null, null, '>'),
            array(100, 0, null, 0, null),
            array(100, 0, null, 0, '<'),
            array(100, 0, null, 0, '!'),
            array(100, 0, null, 0, '^'),
            array(100, 0, null, 0, '>'),
            array(100, 0, null, -1, null),
            array(100, 0, null, -1, '<'),
            array(100, 0, null, -1, '!'),
            array(100, 0, null, -1, '^'),
            array(100, 0, null, -1, '>'),
            array(100, 0, null, 1, null),
            array(100, 0, null, 1, '<'),
            array(100, 0, null, 1, '!'),
            array(100, 0, null, 1, '^'),
            array(100, 0, null, 1, '>'),
            array(100, 0, 0, null, null),
            array(100, 0, 0, null, '<'),
            array(100, 0, 0, null, '!'),
            array(100, 0, 0, null, '^'),
            array(100, 0, 0, null, '>'),
            array(100, 0, 0, 0, null),
            array(100, 0, 0, 0, '<'),
            array(100, 0, 0, 0, '!'),
            array(100, 0, 0, 0, '^'),
            array(100, 0, 0, 0, '>'),
            array(100, 0, 0, -1, null),
            array(100, 0, 0, -1, '<'),
            array(100, 0, 0, -1, '!'),
            array(100, 0, 0, -1, '^'),
            array(100, 0, 0, -1, '>'),
            array(100, 0, 0, 1, null),
            array(100, 0, 0, 1, '<'),
            array(100, 0, 0, 1, '!'),
            array(100, 0, 0, 1, '^'),
            array(100, 0, 0, 1, '>'),
            array(100, 0, -1, null, null),
            array(100, 0, -1, null, '<'),
            array(100, 0, -1, null, '!'),
            array(100, 0, -1, null, '^'),
            array(100, 0, -1, null, '>'),
            array(100, 0, -1, 0, null),
            array(100, 0, -1, 0, '<'),
            array(100, 0, -1, 0, '!'),
            array(100, 0, -1, 0, '^'),
            array(100, 0, -1, 0, '>'),
            array(100, 0, -1, -1, null),
            array(100, 0, -1, -1, '<'),
            array(100, 0, -1, -1, '!'),
            array(100, 0, -1, -1, '^'),
            array(100, 0, -1, -1, '>'),
            array(100, 0, -1, 1, null),
            array(100, 0, -1, 1, '<'),
            array(100, 0, -1, 1, '!'),
            array(100, 0, -1, 1, '^'),
            array(100, 0, -1, 1, '>'),
            array(100, 0, 1, null, null),
            array(100, 0, 1, null, '<'),
            array(100, 0, 1, null, '!'),
            array(100, 0, 1, null, '^'),
            array(100, 0, 1, null, '>'),
            array(100, 0, 1, 0, null),
            array(100, 0, 1, 0, '<'),
            array(100, 0, 1, 0, '!'),
            array(100, 0, 1, 0, '^'),
            array(100, 0, 1, 0, '>'),
            array(100, 0, 1, -1, null),
            array(100, 0, 1, -1, '<'),
            array(100, 0, 1, -1, '!'),
            array(100, 0, 1, -1, '^'),
            array(100, 0, 1, -1, '>'),
            array(100, 0, 1, 1, null),
            array(100, 0, 1, 1, '<'),
            array(100, 0, 1, 1, '!'),
            array(100, 0, 1, 1, '^'),
            array(100, 0, 1, 1, '>'),
        );
    }
}
