name: PHP CI

on: [push]

jobs:
    build-test:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php-version:
                    - '7.2'
                    - '7.3'
                    - '7.4'
                    - '8.0'
        name: PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}
        steps:
            - uses: actions/checkout@v2

            - name: Install ImageMagick
              run: |
                  sudo apt-get update
                  sudo apt-get upgrade -y libjpeg-dev libpng-dev libgif-dev make wget
                  wget https://www.imagemagick.org/download/ImageMagick.tar.gz
                  tar xvzf ImageMagick.tar.gz
                  cd ImageMagick-*
                  ./configure
                  make
                  sudo make install
                  sudo ldconfig /usr/local/lib

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: gd, zip

            - run: composer validate

            - id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - run: composer install

            - run: |
                # export IMAGEMAGICK_PATH="docker run --rm --volume `pwd`:`pwd` --workdir=`pwd` --entrypoint="`pwd`/docker_entrypoint.sh" --user=$UID:$GID dpokidov/imagemagick:latest magick"
                vendor/bin/phpunit
