name: PHP CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version:
                    - '7.2'
                    - '7.3'
                    - '7.4'
                    - '8.0'
                    - '8.1'
                    - '8.2'
                    - '8.3'

                symfony-version:
                    - '5.4'
                    - '6.4'
                    - '7.0'
                    - '7.1'

                exclude:
                    - { php-version: 7.2, symfony-version: 6.4 }
                    - { php-version: 7.2, symfony-version: 7.0 }
                    - { php-version: 7.2, symfony-version: 7.1 }

                    - { php-version: 7.3, symfony-version: 6.4 }
                    - { php-version: 7.3, symfony-version: 7.0 }
                    - { php-version: 7.3, symfony-version: 7.1 }

                    - { php-version: 7.4, symfony-version: 6.4 }
                    - { php-version: 7.4, symfony-version: 7.0 }
                    - { php-version: 7.4, symfony-version: 7.1 }

                    - { php-version: 8.0, symfony-version: 6.4 }
                    - { php-version: 8.0, symfony-version: 7.0 }
                    - { php-version: 8.0, symfony-version: 7.1 }

                    - { php-version: 8.0, symfony-version: 6.4 }
                    - { php-version: 8.1, symfony-version: 7.0 }
                    - { php-version: 8.1, symfony-version: 7.1 }

        name: PHP ${{ matrix.php-version }} and Symfony ${{ matrix.symfony-version }}
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: gd, zip
                  tools: flex

            - run: composer validate

            - id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: 🚧 Setup
              run: composer config extra.symfony.require ^${{ matrix.symfony-version }}

            - name: 🛠 Install
              run: make install

            - name: 🧪 Test
              run: make test
